### ISSUE TITLE
Array and object models are not compared using deep comparison

### ISSUE THREAD

**Issue by vaibhavguptaIITD** [betsol/angular-input-modified#7]
Hi,
Thanks for the great plugin. 

We have been using this plugin recently and had a scenario where we have an array list model bound to a group of checkboxes. Comparison in `valuesEqual` doesn't do a deep compare:
[https://github.com/betsol/angular-input-modified/blob/master/src/angular-input-modified.js#L301](https://github.com/betsol/angular-input-modified/blob/master/src/angular-input-modified.js#L301) 

We have replaced `return (value1 === value2);` with `return _.isEqual(value1, value2);` but this adds a dependency on underscore.

**Comment by slavafomin** [comment]
Hello @vaibhavguptaIITD! Is this issue is still important to you? If so, could you provide additional details please? In other case please close it or I will close it later myself. Thank you!

**Comment by vaibhavguptaIITD** [comment]
Hi,

Sorry for late reply. Let me create a plunker for this.
-- 
Vaibhav Gupta
Sent with Airmail

On 4 January 2015 at 5:26:38 pm, Slava Fomin (notifications@github.com) wrote:

Hello @vaibhavguptaIITD! Is this issue is still important to you? If so, could you provide additional details please? In other case please close it or I will close it later myself. Thank you!

**Comment by slavafomin** [comment]
I've released a new major version of the module just now. Make sure that you are using the latest version. Thanks!

**Comment by slavafomin** [comment]
I've updated the [Demo Plunk](http://plnkr.co/edit/g2MDXv81OOBuGo6ORvdt?p=preview). Feel free to fork it.

**Comment by vaibhavguptaIITD** [comment]
Hi,

Following is the plunker:

http://plnkr.co/edit/qUVZuVqI0o54wkrjAqkz?p=preview

I have a multi select for list of fruits. It was initialised the model user.favoriteFruit with ['Banana']. However, if I select Mango and again select Banana, the model is still shown as modified but it has been restored to its initial value.



-- 
Vaibhav Gupta
Sent with Airmail

On 4 January 2015 at 7:34:34 pm, Slava Fomin (notifications@github.com) wrote:

I've updated the Demo Plunk. Feel free to fork it.

**Comment by slavafomin** [comment]
Okay, now I understand the problem. Thank you )
Please give me some time, I will get back to you.

**Comment by vaibhavguptaIITD** [comment]
Hi,

I have managed a workaround by using underscore.js. But I think that would be a dependency on another library.
-- 
Vaibhav Gupta
Sent with Airmail

On 4 January 2015 at 8:30:17 pm, Slava Fomin (notifications@github.com) wrote:

Okay, now I understand the problem. Thank you )
Please give me some time, I will get back to you.

**Comment by slavafomin** [comment]
I've just pushed another commit. Please see [this example](http://betsol.github.io/angular-input-modified/select-multiple/) and tell me if it helps.

**Comment by vaibhavguptaIITD** [comment]
Hi,

Thank you for the fix. It works perfectly now. 
-- 
Vaibhav Gupta
Sent with Airmail

On 4 January 2015 at 8:42:58 pm, Slava Fomin (notifications@github.com) wrote:

I've just pushed another commit. Please see this example and tell me if it helps.

**Comment by slavafomin** [comment]
I've released a new version of the library that addresses this issue. If you need any further support - please let me know. Thanks.
